export interface GetUsersData {
  userBadges: [{}];
  user: {
    id: number,
    username: string,
    avatarTemplate: string,
    name: {},
    lastPostedAt: string,
    lastSeenAt: string,
    createdAt: string,
    websiteName: {},
    canEdit: true,
    canEditUsername: true,
    canEditEmail: true,
    canEditName: true,
    canSendPrivateMessages: true,
    canSendPrivateMessageToUser: true,
    trustLevel: number,
    moderator: true,
    admin: true,
    title: {},
    uploadedAvatarId: {},
    badgeCount: number,
    customFields: {},
    pendingCount: number,
    profileViewCount: number,
    primaryGroupName: {},
    primaryGroupFlairUrl: {},
    primaryGroupFlairBgColor: {},
    primaryGroupFlairColor: {},
    invitedBy: {},
    groups: [
      {
        id: number,
        automatic: true,
        name: string,
        userCount: number,
        aliasLevel: number,
        visible: true,
        automaticMembershipEmailDomains: {},
        automaticMembershipRetroactive: true,
        primaryGroup: true,
        title: {},
        grantTrustLevel: {},
        notificationLevel: {},
        hasMessages: true,
        isMember: true,
        mentionable: true,
        flairUrl: {},
        flairBgColor: {},
        flairColor: {},
      },
    ],
    featuredUserBadgeIds: [{}],
    cardBadge: {},
  };
}

export type DiscourseUser = {
  id: number,
  username: string,
  name: string,
  avatarTemplate: string,
};
