export interface GetUsersData {
  user_badges: [{}];
  user: {
    id: 0,
    username: 'string',
    avatar_template: 'string',
    name: {},
    last_posted_at: 'string',
    last_seen_at: 'string',
    created_at: 'string',
    website_name: {},
    can_edit: true,
    can_edit_username: true,
    can_edit_email: true,
    can_edit_name: true,
    can_send_private_messages: true,
    can_send_private_message_to_user: true,
    trust_level: 0,
    moderator: true,
    admin: true,
    title: {},
    uploaded_avatar_id: {},
    badge_count: 0,
    custom_fields: {},
    pending_count: 0,
    profile_view_count: 0,
    primary_group_name: {},
    primary_group_flair_url: {},
    primary_group_flair_bg_color: {},
    primary_group_flair_color: {},
    invited_by: {},
    groups: [
      {
        id: 0,
        automatic: true,
        name: 'string',
        user_count: 0,
        alias_level: 0,
        visible: true,
        automatic_membership_email_domains: {},
        automatic_membership_retroactive: true,
        primary_group: true,
        title: {},
        grant_trust_level: {},
        notification_level: {},
        has_messages: true,
        is_member: true,
        mentionable: true,
        flair_url: {},
        flair_bg_color: {},
        flair_color: {},
      },
    ],
    featured_user_badge_ids: [{}],
    card_badge: {},
  };
}
